os: linux
sudo: required
language:
- minimal
services:
- docker

jobs:
  include:
    - name: "compile"
        script:
          - docker run -t -v $(pwd):/var/builder/ -w /var/builder --entrypoint ./scripts/compile.sh $DOCKER_IMAGE

notifications:
    email: false
